.MODEL SMALL
 .STACK 100H
 
 .DATA
  ; NM DB 'C:\DD',00H
   MSG1 DB "ENTER DIRECTORY NAME: $"
   ;MSG2 DB 0AH,0DH,"
   STR1 DB 30 DUP()
  .CODE
	MAIN PROC
	MOV AX,@DATA
	MOV DS,AX
	
	LEA DX,MSG1 ;SHOW ENTER A STRING
	MOV AH,09H
	INT 21H
	
	LEA SI,STR1
	MOV CL,00H ; INITALIZE COUNTER 
	RP:
	MOV AH,01H ;READ A CHAR
	INT 21H	
	CMP AL,0DH ;CONPARE WITH NEW LINE CHAR
	JZ FINISH
	MOV [SI],AL ; MOVE READ CHAR TO STRING AND INCREMT COUNTS
	INC SI
	INC CL
	JMP RP
	FINISH:
	MOV AL,00H
	MOV [SI],AL ;$ CHAR
	;FINISHED READING STRING
	
	LEA DX, STR1
	
	MOV AH,39H
	INT 21H
	
	MOV AX,4C00H
	INT 21H
	
	MAIN ENDP
	END MAIN